using App.Application.DTOs;
using App.Application.Interfaces;
using App.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace App.Application.Services;

public class ReportService : IReportService
{
    private sealed record NormalizedDraftRow(
        Guid LivestockEventId,
        string AccountCode,
        string EntryType,
        decimal DebitAmount,
        decimal CreditAmount,
        int HeadCount,
        decimal WeightKg,
        Guid? FieldId,
        string FieldName,
        Guid? ActivityId,
        string ActivityName,
        Guid? CategoryId,
        string CategoryName);

    private readonly IApplicationDbContext _context;

    public ReportService(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<BalanceItemDto>> GetBalanceAsync(
        Guid? fieldId,
        Instant? startDate,
        Instant? endDate,
        string categoryView,
        Guid tenantId,
        Guid? categoryId)
    {
        var query = _context.AccountingDrafts
            .AsNoTracking()
            .Where(a => a.TenantId == tenantId)
            .AsQueryable();

        if (fieldId.HasValue)
            query = query.Where(a => a.FieldId == fieldId.Value);

        if (categoryId.HasValue)
            query = query.Where(a => a.CategoryId == categoryId.Value);

        if (startDate.HasValue)
            query = query.Where(a => a.LivestockEvent != null && a.LivestockEvent.EventDate >= startDate.Value);

        if (endDate.HasValue)
            query = query.Where(a => a.LivestockEvent != null && a.LivestockEvent.EventDate <= endDate.Value);

        // Defensive normalization: collapses exact duplicated drafts (same event + account + amounts + dimensions)
        // to avoid double-counting balances when duplicate rows were generated by retries.
        var deduplicatedRows = await query
            .GroupBy(a => new
            {
                a.LivestockEventId,
                a.AccountCode,
                a.EntryType,
                a.DebitAmount,
                a.CreditAmount,
                a.HeadCount,
                WeightKg = a.WeightKg ?? 0m,
                a.FieldId,
                a.ActivityId,
                a.CategoryId
            })
            .Select(g => new NormalizedDraftRow(
                g.Key.LivestockEventId,
                g.Key.AccountCode,
                g.Key.EntryType,
                g.Key.DebitAmount,
                g.Key.CreditAmount,
                g.Key.HeadCount,
                g.Key.WeightKg,
                g.Key.FieldId,
                string.Empty,
                g.Key.ActivityId,
                string.Empty,
                g.Key.CategoryId,
                string.Empty))
            .ToListAsync();

        var fieldIds = deduplicatedRows
            .Where(x => x.FieldId.HasValue)
            .Select(x => x.FieldId!.Value)
            .Distinct()
            .ToList();
        var activityIds = deduplicatedRows
            .Where(x => x.ActivityId.HasValue)
            .Select(x => x.ActivityId!.Value)
            .Distinct()
            .ToList();
        var categoryIds = deduplicatedRows
            .Where(x => x.CategoryId.HasValue)
            .Select(x => x.CategoryId!.Value)
            .Distinct()
            .ToList();

        var fieldNames = await _context.Fields
            .AsNoTracking()
            .Where(f => fieldIds.Contains(f.Id))
            .ToDictionaryAsync(f => f.Id, f => f.Name);
        var activityNames = await _context.Activities
            .AsNoTracking()
            .Where(a => activityIds.Contains(a.Id))
            .ToDictionaryAsync(a => a.Id, a => a.Name);
        var categoryNames = await _context.AnimalCategories
            .AsNoTracking()
            .Where(c => categoryIds.Contains(c.Id))
            .ToDictionaryAsync(c => c.Id, c => c.Name);

        var normalizedRows = deduplicatedRows.Select(r => r with
        {
            FieldName = r.FieldId.HasValue && fieldNames.TryGetValue(r.FieldId.Value, out var fieldName)
                ? fieldName
                : "Sin Campo",
            ActivityName = r.ActivityId.HasValue && activityNames.TryGetValue(r.ActivityId.Value, out var activityName)
                ? activityName
                : "Sin Actividad",
            CategoryName = r.CategoryId.HasValue && categoryNames.TryGetValue(r.CategoryId.Value, out var categoryName)
                ? categoryName
                : "Sin Categoría"
        }).ToList();

        if (categoryView == "gestor")
        {
            var mappingByClientCategory = await _context.CategoryMappings
                .AsNoTracking()
                .Where(m => m.TenantId == tenantId)
                .GroupBy(m => m.CategoriaClienteId)
                .Select(g => new
                {
                    CategoriaClienteId = g.Key,
                    CategoriaGestorId = g.Select(x => x.CategoriaGestorId).FirstOrDefault()
                })
                .ToDictionaryAsync(x => x.CategoriaClienteId, x => x.CategoriaGestorId);

            var gestorCategoriesByExternalId = await _context.AnimalCategories
                .AsNoTracking()
                .Where(c => c.Type == CategoryType.Gestor && c.TenantId == tenantId)
                .Where(c => c.ExternalId != null)
                .ToDictionaryAsync(c => c.ExternalId!, c => c.Name);

            return normalizedRows
                .GroupBy(a =>
                {
                    var mappedName = a.CategoryId.HasValue
                        && mappingByClientCategory.TryGetValue(a.CategoryId.Value, out var gestorId)
                        && !string.IsNullOrWhiteSpace(gestorId)
                        && gestorCategoriesByExternalId.TryGetValue(gestorId, out var gestorCategoryName)
                            ? gestorCategoryName
                            : a.CategoryName;

                    return new
                    {
                        a.AccountCode,
                        a.FieldName,
                        a.ActivityName,
                        CategoryName = mappedName
                    };
                })
                .Select(g => new BalanceItemDto(
                    g.Key.FieldName,
                    g.Key.CategoryName,
                    g.Sum(a => a.EntryType == "DEBE" ? a.HeadCount : -a.HeadCount),
                    g.Sum(a => a.EntryType == "DEBE" ? a.WeightKg : -a.WeightKg),
                    g.Key.ActivityName,
                    g.Key.AccountCode,
                    g.Sum(a => a.DebitAmount),
                    g.Sum(a => a.CreditAmount),
                    g.Sum(a => a.DebitAmount - a.CreditAmount),
                    g.Sum(a => a.WeightKg),
                    DeriveGroup(g.Key.AccountCode)))
                .ToList();
        }

        var resultQuery = normalizedRows
            .GroupBy(a => new
            {
                a.AccountCode,
                a.FieldName,
                a.ActivityName,
                a.CategoryName
            })
            .Select(g => new BalanceItemDto(
                g.Key.FieldName,
                g.Key.CategoryName,
                g.Sum(a => a.EntryType == "DEBE" ? a.HeadCount : -a.HeadCount),
                g.Sum(a => a.EntryType == "DEBE" ? a.WeightKg : -a.WeightKg),
                g.Key.ActivityName,
                g.Key.AccountCode,
                g.Sum(a => a.DebitAmount),
                g.Sum(a => a.CreditAmount),
                g.Sum(a => a.DebitAmount - a.CreditAmount),
                g.Sum(a => a.WeightKg),
                DeriveGroup(g.Key.AccountCode)));

        return resultQuery.ToList();
    }

    public async Task<IEnumerable<LedgerEntryDto>> GetLedgerAsync(
        Instant? startDate, Instant? endDate,
        int pageIndex, int pageSize,
        string? searchTerm, Guid tenantId,
        string? accountCode, Guid? categoryId, Guid? fieldId)
    {
        var query = _context.AccountingDrafts
            .AsNoTracking()
            .Where(a => a.TenantId == tenantId)
            .AsQueryable();

        if (startDate.HasValue)
            query = query.Where(a => a.LivestockEvent != null && a.LivestockEvent.EventDate >= startDate.Value);

        if (endDate.HasValue)
            query = query.Where(a => a.LivestockEvent != null && a.LivestockEvent.EventDate <= endDate.Value);

        if (!string.IsNullOrWhiteSpace(searchTerm))
            query = query.Where(a => a.Concept.Contains(searchTerm) || a.AccountCode.Contains(searchTerm));

        if (!string.IsNullOrWhiteSpace(accountCode))
            query = query.Where(a => a.AccountCode == accountCode);

        if (categoryId.HasValue)
            query = query.Where(a => a.CategoryId == categoryId.Value);

        if (fieldId.HasValue)
            query = query.Where(a => a.FieldId == fieldId.Value);

        return await query
            .OrderByDescending(a => a.LivestockEvent != null ? a.LivestockEvent.EventDate : a.CreatedAt)
            .Skip(pageIndex * pageSize)
            .Take(pageSize)
            .Select(a => new LedgerEntryDto(
                a.Id,
                a.LivestockEvent != null ? a.LivestockEvent.EventDate : a.CreatedAt,
                a.Concept,
                a.DebitAmount > 0 ? a.DebitAmount : a.CreditAmount,
                a.AccountCode,
                a.LivestockEvent != null ? a.LivestockEvent.Status.ToString() : "Draft",
                a.EntryType,
                a.HeadCount,
                a.WeightKg ?? 0,
                a.LivestockEventId,
                a.Field != null ? a.Field.Name : "",
                a.Category != null ? a.Category.Name : "",
                a.DebitAmount,
                a.CreditAmount))
            .ToListAsync();
    }

    private static string DeriveGroup(string accountCode)
    {
        if (string.IsNullOrEmpty(accountCode)) return "RESULTADO";
        return accountCode[0] switch
        {
            '1' => "ACTIVO",
            '2' => "PASIVO",
            _ => "RESULTADO"
        };
    }
}

